targets:
  $default:
    builders:
      reflectable:
        enabled: true
        generate_for:
          - lib/main.dart
        options:
          formatted: true
      built_value_generator|built_value:
        enabled: true
      json_serializable:
        enabled: false
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          #
          # For usage information, reference the corresponding field in
          # `JsonSerializableGenerator`.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generate_to_json_function: true
          include_if_null: true
          nullable: true
          use_wrappers: false